// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlgATxStKTJu5xnV94YvEKvsTAVltvFpU',
    appId: '1:430564965079:web:487e52ae2d292fc02d0e92',
    messagingSenderId: '430564965079',
    projectId: 'portfoliobuilderslms',
    authDomain: 'portfoliobuilderslms.firebaseapp.com',
    storageBucket: 'portfoliobuilderslms.firebasestorage.app',
    measurementId: 'G-G0NBL51MVF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWdORxqmsC3mmORmAgmdYlM6pvoP8Perg',
    appId: '1:430564965079:android:d1e531019419dd2c2d0e92',
    messagingSenderId: '430564965079',
    projectId: 'portfoliobuilderslms',
    storageBucket: 'portfoliobuilderslms.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApHu-zIVtjECrMmxZ2LNuYybQtjBnttJI',
    appId: '1:430564965079:ios:c0cee34a577e9b812d0e92',
    messagingSenderId: '430564965079',
    projectId: 'portfoliobuilderslms',
    storageBucket: 'portfoliobuilderslms.firebasestorage.app',
    iosBundleId: 'com.example.gtech',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApHu-zIVtjECrMmxZ2LNuYybQtjBnttJI',
    appId: '1:430564965079:ios:c0cee34a577e9b812d0e92',
    messagingSenderId: '430564965079',
    projectId: 'portfoliobuilderslms',
    storageBucket: 'portfoliobuilderslms.firebasestorage.app',
    iosBundleId: 'com.example.gtech',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAlgATxStKTJu5xnV94YvEKvsTAVltvFpU',
    appId: '1:430564965079:web:5f7861aaaefd33fc2d0e92',
    messagingSenderId: '430564965079',
    projectId: 'portfoliobuilderslms',
    authDomain: 'portfoliobuilderslms.firebaseapp.com',
    storageBucket: 'portfoliobuilderslms.firebasestorage.app',
    measurementId: 'G-3MCERBBSYK',
  );
}
